runtime! archlinux.vim

syntax on
filetype on

set nu
set list
set listchars=tab:>-,trail:-
set completeopt=preview,menu
set clipboard=unnamed
set nobackup
set noswapfile
set ruler
set cursorline
set nocompatible
set softtabstop=4
set shiftwidth=4

set confirm
set backspace=2
set encoding=utf-8
set langmenu=zh_CN.UTF-8
language message zh_CN.UTF-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
