RIGHT no-osd seek 5 #event: click
RIGHT no-osd set speed 3; set pause no #event: press
RIGHT ignore #event: release

q playlist-prev #播放列表上一个
e playlist-next #播放列表下一个
a add chapter -1 #视频上一章节
d add chapter 1 #视频下一章节
p set speed 1.0 #播放速度设为1
TAB script-binding stats/display-stats-toggle #打开播放信息
