#有不懂的，比如vo，可以执行"mpv --vo=help"来查看文档

#启用实验性的GPU驱动
vo=gpu-next
#Pipewire音频驱动
ao=pipewire
#VAAPI硬解
hwdec=vaapi
#启用Vulkan
gpu-api=vulkan
gpu-context=waylandvk
#尝试硬解所有格式
hwdec-codecs=all
#窗口最大化
window-maximized=yes
#开启缓存
cache=yes
#用内存而不是磁盘缓存
cache-on-disk=no
#缓存时间
cache-secs=10
#播完后不退出
keep-open=yes
#变速播放时的音调修正
audio-pitch-correction=yes
#字幕字体大小
sub-font-size=60
#未指定样式的字幕字体
sub-font="Source Han Sans CN"
#未指定样式的字幕边框
sub-border-size=2
#强制外挂ass字幕可使用黑边
sub-ass-force-margins=yes
#指定优先使用音轨（使用ISO-639语言代码，优先级按序递减）
alang=zh,chi,chs,sc,zh-hans,en,eng
#指定优先使用字幕轨（同上）
slang=zh,chi,chs,sc,zh-hans,en,eng
#列表无限循环
loop-playlist=inf
#截屏文件格式
screenshot-format=avif
#截屏文件保存路径
screenshot-directory=/home/lin/img/mpv

#高画质渲染模式，0.37.0后默认启用
profile=high-quality

#高性能低功耗模式，适合低性能设备
#profile=fast
#关闭默认GUI
osc=no
