##解码/渲染设置##

#视频输出驱动，可选gpu/gpu-next，gpu最成熟稳定，gpu-next为实验性
vo=gpu
ao=pipewire
hwdec=vaapi
gpu-api=vulkan
#尝试使用硬解的格式(默认h264,vc1,hevc,vp8,vp9,av1；all是特殊值指全部格式)
hwdec-codecs=all

--geometry=1366x710
##缓存设置##

#开启缓存
cache=yes
#用内存而不是磁盘缓存
cache-on-disk=no
#缓存时间
cache-secs=10

#播完后不退出
keep-open=yes
#拖入文件行为设置（no/auto/replace/append)。no禁用拖入，auto根据平台自动选择，replace替换当前文件并播放，append将拖入的文件添加到播放列表。默认是拖入replace，按住shift拖入append
drag-and-drop=no

#变速播放时的音调修正
audio-pitch-correction=yes
sub-font-size=60
#未指定样式的字幕字体
sub-font="Source Han Sans CN"
#未指定样式的字幕边框
sub-border-size=2
#强制外挂ass字幕可使用黑边
sub-ass-force-margins=yes
#指定优先使用音轨（使用ISO-639语言代码，优先级按序递减）
alang=zh,chi,chs,sc,zh-hans,en,eng
#指定优先使用字幕轨（同上）
slang=zh,chi,chs,sc,zh-hans,en,eng
#列表播放循环方式，N|inf|no，循环N次/一直循环/不循环
loop-playlist=inf
#截屏文件格式（可选：jpg、png、webp、jxl、avif）
screenshot-format=avif
#截屏文件保存路径
screenshot-directory=/home/lin/img/mpv

#高画质渲染模式，0.37.0后默认启用
profile=high-quality

#高性能低功耗模式，适合低性能设备
#profile=fast

osc=no
