--gtk-version=3
--enable-wayland-ime
--wayland-text-input-version=1
--enable-download-warning-improvements

#禁用垂直同步
--disable-gpu-vsync
#忽略GPU黑名单，强制启用硬件解码
--ignore-gpu-blocklist
#Wayland
--ozone-platform=wayland
#解决密钥环问题
--password-store=basic
#GPU光栅化
--enable-gpu-rasterization
#QUIC/HTTP3
--enable-quic
#零拷贝
--enable-zero-copy
#平滑滚动
--enable-smooth-scrolling
#硬件解码
--enable-accelerated-video-decode
#钱包服务沙盒
--wallet-service-use-sandbox=0
#Ozone平台，Wayland窗口装饰，WebRTC的Pipewire支持
#Vulkan,VAAPI,TLSv1.3,多线程下载,HEVC

--enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer,VaapiVideoDecoder,VaapiVideoEncoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,CanvasOopRasterization,EnableDrDc,EnableTLS13EarlyData,ParallelDownloading,PlatformHEVCDecoderSupport,WebRtcPipeWireCamera

