--disable-gpu-vsync
--ignore-gpu-blocklist
--ozone-platform=wayland
--password-store=basic
--gtk-version=4
--enable-download-warning-improvements
--enable-gpu-rasterization
--enable-quic
--enable-zero-copy
--enable-smooth-scrolling
--enable-accelerated-video-decode
--wallet-service-use-sandbox=0
--enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer,VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,CanvasOopRasterization,EnableDrDc,EnableTLS13EarlyData,ParallelDownloading
